apiVersion: v2
name: kro
description: Kubernetes Resource Optimization (KRO)
version: 0.1.0
type: application
dependencies:
  - name: kro
    version: "0.4.0"  # Will be replaced with latest version
    repository: oci://ghcr.io/kro-run/kro
