apiVersion: v2
name: kro
description: Kubernetes Resource Optimization (KRO)
version: 0.1.0
type: application
dependencies:
  - name: kro
    version: "0.2.1"  # Will be replaced with latest version
    repository: oci://public.ecr.aws/kro
