kro:
  nameOverride: kro
  fullnameOverride: kro

  rbac:
    create: true

  serviceAccount:
    create: true
    name: kro-sa
    annotations: {}

  deployment:
    replicas: 1

  config:
    rules:
      - name: "pod-resources"
        target: "Pod"
        conditions:
          - field: "spec.containers[*].resources"
            operation: "exists"

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

  nodeSelector:
    kubernetes.io/os: linux

  tolerations: []
  
  affinity: {}
