apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  helm.repositories: |
    - name: aws-controllers-k8s
      url: oci://public.ecr.aws/aws-controllers-k8s
    - name: kro
      url: oci://public.ecr.aws/kro/kro
