apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-demo-workload-3-karpenter-core
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: default
  source:
    repoURL: https://github.com/kumudhanrajan18/gitops-system.git
    targetRevision: HEAD
    path: accounts/dev/clusters/demo-workload-3/karpenter/core
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://CA1ED1A1482FB06EB475023B875B7509.gr7.eu-west-1.eks.amazonaws.com
    namespace: karpenter
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
