# management/addons/ack/values.yaml
iam-chart:
  aws:
    region: us-west-2
  
  serviceAccount:
    create: true
    name: iam-ack
    namespace: default  # Changed to default
    annotations: {}
  
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 128Mi
  
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
  
  nodeSelector:
    kubernetes.io/os: linux

  webhook:
    enabled: true
    port: 9443

  deployment:
    namespace: default
    healthCheckPort: 8080
    metricsPort: 8080
