iam-chart:
  aws:
    region: eu-west-1
  image:
    platform: linux/amd64
  serviceAccount:
    create: true
    name: iam-ack
    namespace: ack-system
    annotations: {}
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 128Mi
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
  nodeSelector:
    kubernetes.io/os: linux
  webhook:
    enabled: true
    port: 9443
  deployment:
    namespace: ack-system
    healthCheckPort: 8080
    metricsPort: 8080
