apiVersion: kro.run/v1alpha1
kind: KarpenterCore
metadata:
  name: dev-demo-workload-1-karpenter
spec:
  name: demo-workload-1
  namespace: kro-system
  oidcRef:
    name: demo-workload-1-oidc
    namespace: kro-system

