
eks-chart:
  aws:
    region: eu-west-1
  
  serviceAccount:
    create: true
    name: eks-ack
    annotations: {}
  
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 128Mi
  
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
  
  nodeSelector:
    kubernetes.io/os: linux

  webhook:
    enabled: true
    port: 9443
