accountId: "208875563909"
karpenter:
  serviceAccount:
    name: "karpenter"
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::208875563909:role/dev-demo-workload-2-karpenter-controller"

  settings:
    clusterName: "dev-demo-workload-2"
    interruptionQueue: "dev-demo-workload-2-spot-interruption"

  dnsPolicy: "Default"
  controller:
    env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: "regional"
      - name: AWS_DEFAULT_REGION
        value: "eu-west-1"
      - name: CLUSTER_ENDPOINT
        value: https://71CBB5D3FD001591860045738821E970.gr7.eu-west-1.eks.amazonaws.com
    healthProbe:
      port: 8081
    readinessProbe:
      initialDelaySeconds: 600
      timeoutSeconds: 300
      periodSeconds: 15
      failureThreshold: 3
    livenessProbe:
      initialDelaySeconds: 540
      timeoutSeconds: 300
      periodSeconds: 15
      failureThreshold: 3

  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"

    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000

