karpenter:
  accountId: "208875563909"
  serviceAccount:
    name: "karpenter"
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::208875563909:role/dev-demo-workload-1-karpenter-controller"

  settings:
    clusterName: "demo-workload-1"

  dnsPolicy: "Default"
  controller:
    env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: "regional"
      - name: AWS_DEFAULT_REGION
        value: "eu-west-1"
      - name: CLUSTER_ENDPOINT
        value: "https://9C194494D8F80D4A8806EB2E0F017065.gr7.eu-west-1.eks.amazonaws.com"
    healthProbe:
      port: 8081
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10
      periodSeconds: 15
      failureThreshold: 3
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10
      periodSeconds: 15
      failureThreshold: 3

  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"

    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000

