apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-demo-workload-1-karpenter-core
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          tenant: workload
  template:
    metadata:
      name: dev-demo-workload-1-karpenter-core
      annotations:
        argocd.argoproj.io/sync-wave: "6"
    spec:
      project: default
      source:
        repoURL: https://github.com/kumudhanrajan18/gitops-system.git
        targetRevision: HEAD
        path: accounts/dev/clusters/demo-workload-1/karpenter/core
        helm:
          valueFiles:
          - values.yaml
      destination:
        server: '{{server}}'
        namespace: karpenter
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
