apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-demo-workload-1-karpenter-infra
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: dev-demo-workload-1-karpenter-infra
            oidcProviderArn: '{{ from "demo-workload-1-cluster-info" .Data.oidc_provider_arn }}'
            oidcProviderUrl: '{{ from "demo-workload-1-cluster-info" .Data.oidc_provider_url }}'
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/kumudhanrajan18/gitops-system.git
        targetRevision: HEAD
        path: accounts/dev/clusters/demo-workload-1/karpenter/infra
        helm:
          parameters:
            - name: cluster.oidc.providerArn
              value: '{{oidcProviderArn}}'
            - name: cluster.oidc.providerUrl
              value: '{{oidcProviderUrl}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: kro-system
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
