apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-demo-workload-1-karpenter-core
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          tenant: dev-demo-workload-1
  template:
    metadata:
      name: dev-demo-workload-1-karpenter-core
      annotations:
        argocd.argoproj.io/sync-wave: "6"
    spec:
      project: default
      sources:
      - repoURL: https://charts.karpenter.sh
        targetRevision: v0.33.0
        chart: karpenter
        helm:
          valueFiles:
          - $values/values.yaml
          - $values/values-common.yaml
          values: |
            global:
              clusterName: demo-workload-1
      - repoURL: https://github.com/kumudhanrajan18/gitops-system.git
        targetRevision: HEAD
        path: accounts/dev/clusters/{{name}}/karpenter/values
        ref: values
      - repoURL: https://github.com/kumudhanrajan18/gitops-system.git
        targetRevision: HEAD
        path: accounts/dev/clusters/{{name}}/karpenter/core
      destination:
        server: '{{server}}'
        namespace: karpenter
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
