apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-demo-workload-1-karpenter-infra
  namespace: argocd
spec:
  generators:
    - configMap:
        name: demo-workload-1-cluster-info
        namespace: argocd
        generate:
          items:
            - name: oidc_provider_arn
              key: oidc_provider_arn
            - name: oidc_provider_url
              key: oidc_provider_url
  template:
    metadata:
      name: 'dev-demo-workload-1-karpenter-infra'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "5"
    spec:
      project: default
      source:
        repoURL: https://github.com/kumudhanrajan18/gitops-system.git
        targetRevision: HEAD
        path: accounts/dev/clusters/demo-workload-1/karpenter/infra
        directory:
          jsonnet:
            extVars:
              - name: oidc_provider_arn
                value: '{{oidc_provider_arn}}'
              - name: oidc_provider_url
                value: '{{oidc_provider_url}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: kro-system
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
