apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-demo-workload-1-karpenter-infra
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: dev-demo-workload-1-karpenter-infra
  template:
    metadata:
      name: dev-demo-workload-1-karpenter-infra
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/kumudhanrajan18/gitops-system.git
        targetRevision: HEAD
        path: accounts/dev/clusters/demo-workload-1/karpenter/infra
      destination:
        server: https://kubernetes.default.svc
        namespace: kro-system
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
