apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-infrastructure
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: dev-infrastructure
  template:
    metadata:
      name: 'dev-infrastructure'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "3"  # After Accounts AS
    spec:
      project: default
      source:
        repoURL: https://github.com/kumudhanrajan18/gitops-system.git
        targetRevision: HEAD
        path: accounts/dev/infrastructure
      destination:
        server: https://kubernetes.default.svc
        namespace: kro-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
