ec2-chart:
  aws:
    region: eu-west-1

  serviceAccount:
    create: true
    name: ec2-ack
    namespace: ack-system

  deployment:
    namespace: ack-system

  livenessProbe:
    httpGet:
      path: /healthz
      port: 8080  # Changed from 8080
    initialDelaySeconds: 60  # Increased delay
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 3

  readinessProbe:
    httpGet:
      path: /readyz
      port: 8080  # Changed from 8080
    initialDelaySeconds: 60  # Increased delay
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 3

  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 128Mi

  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"

  nodeSelector:
    kubernetes.io/os: linux

  webhook:
    enabled: true
    port: 9443
