apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "{{ .Values.karpenter.accountId | quote }}"
  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: "{{ .Values.karpenter.settings.clusterName | quote }}"
  role: "{{ .Values.karpenter.settings.clusterName | quote }}-instance-profile-role"
  tags:
    karpenter.sh/discovery: "{{ .Values.karpenter.settings.clusterName | quote }}""
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required