apiVersion: kro.run/v1alpha1
kind: ResourceGroup
metadata:
  name: karpenter.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: KarpenterCore
    spec:
      name: string
      namespace: string
      configMapRef:
        name: string
        namespace: string
  watchResources:
    - group: ""
      version: v1
      kind: ConfigMap
  resources:
  - id: karpenterNamespace
    template:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: karpenter

  - id: karpenterServiceAccount
    template:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: karpenter
        namespace: karpenter
        annotations:
          eks.amazonaws.com/role-arn: "{{ (lookup \"v1\" \"configmap\" ${schema.spec.configMapRef.namespace} ${schema.spec.configMapRef.name}).data.controller_role_arn }}"