apiVersion: kro.run/v1alpha1
kind: ResourceGroup
metadata:
  name: karpenter.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: KarpenterCore
    spec:
      name: string
      namespace: string
      oidcRef:
        name: string
        namespace: string
  resources:
  # - id: karpenterNamespace
  #   template:
  #     apiVersion: v1
  #     kind: Namespace
  #     metadata:
  #       name: karpenter

  - id: clusterInfo
    template:
      apiVersion: services.k8s.aws/v1alpha1
      kind: AdoptedResource
      metadata:
        name: ${schema.spec.name}-cluster-info
        namespace: ${schema.spec.namespace}
      spec:
        aws:
          nameOrID: ${schema.spec.secretRef.name}
        kubernetes:
          group: "secretsmanager.services.k8s.aws"
          kind: Secret
          metadata:
            name: ${schema.spec.secretRef.name}
            namespace: ${schema.spec.secretRef.namespace}

  - id: nodeRole
    template:
      apiVersion: iam.services.k8s.aws/v1alpha1
      kind: Role
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-cluster-node-role
      spec:
        name: ${schema.spec.name}-cluster-node-role
        policies:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        assumeRolePolicyDocument: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Service": "ec2.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
              }
            ]
          }

  - id: karpenterControllerRole
    dependsOn:
      - oidcProvider
    template:
      apiVersion: iam.services.k8s.aws/v1alpha1
      kind: Role
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-karpenter-controller
      spec:
        name: ${schema.spec.name}-karpenter-controller
        assumeRolePolicyDocument: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Federated": "${adopted("${schema.spec.name}-cluster-info").value.controller_role_arn}"
                },
                "Action": "sts:AssumeRoleWithWebIdentity",
                "Condition": {
                  "StringEquals": {
                    "${clusterInfo.spec.aws.value.oidc_provider_url}:aud": "sts.amazonaws.com",
                    "${clusterInfo.spec.aws.value.oidc_provider_url}:sub": "system:serviceaccount:karpenter:karpenter"
                  }
                }
              }
            ]
          }
        inlinePolicies:
          karpenter-policy: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "ec2:CreateLaunchTemplate",
                    "ec2:CreateFleet",
                    "ec2:RunInstances",
                    "ec2:CreateTags",
                    "iam:PassRole",
                    "ec2:TerminateInstances",
                    "ec2:DescribeLaunchTemplates",
                    "ec2:DescribeInstances",
                    "ec2:DescribeSecurityGroups",
                    "ec2:DescribeSubnets",
                    "ec2:DescribeInstanceTypes",
                    "ec2:DescribeInstanceTypeOfferings",
                    "ec2:DescribeAvailabilityZones",
                    "ssm:GetParameter"
                  ],
                  "Resource": "*"
                }
              ]
            }

  - id: karpenterInstanceProfile
    dependsOn:
      - nodeRole
    template:
      apiVersion: iam.services.k8s.aws/v1alpha1
      kind: InstanceProfile
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-karpenter-instance-profile
      spec:
        name: ${schema.spec.name}-karpenter-instance-profile
        role: ${schema.spec.name}-cluster-node-role

  - id: karpenterServiceAccount
    dependsOn:
      - clusterConfigMap
    template:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: karpenter-test
        namespace: karpenter
        annotations:
          eks.amazonaws.com/role-arn: ${karpenterControllerRole.status.ackResourceMetadata.arn}