apiVersion: kro.run/v1alpha1
kind: ResourceGroup
metadata:
  name: karpenter.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: KarpenterCore
    spec:
      name: string
      namespace: string
      region: string
      accountId: string
      oidc_provider_arn: string
      oidc_provider_url: string
  resources:
  - id: nodeRole
    template:
      apiVersion: iam.services.k8s.aws/v1alpha1
      kind: Role
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-cluster-node-role
      spec:
        name: ${schema.spec.name}-cluster-node-role
        policies:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        assumeRolePolicyDocument: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Service": "ec2.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
              }
            ]
          }

  - id: karpenterControllerRole
    template:
      apiVersion: iam.services.k8s.aws/v1alpha1
      kind: Role
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-karpenter-controller
      spec:
        name: ${schema.spec.name}-karpenter-controller
        assumeRolePolicyDocument: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Federated": "${schema.spec.oidc_provider_arn}"
                },
                "Action": "sts:AssumeRoleWithWebIdentity",
                "Condition": {
                  "StringEquals": {
                    "${schema.spec.oidc_provider_url}:aud": "sts.amazonaws.com",
                    "${schema.spec.oidc_provider_url}:sub": "system:serviceaccount:karpenter:karpenter"
                  }
                }
              }
            ]
          }
        inlinePolicies:
          karpenter-policy: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Action": [
                    "ssm:GetParameter",
                    "ec2:DescribeImages",
                    "ec2:RunInstances",
                    "ec2:DescribeSubnets",
                    "ec2:DescribeSecurityGroups",
                    "ec2:DescribeLaunchTemplates",
                    "ec2:DescribeInstances",
                    "ec2:DescribeInstanceTypes",
                    "ec2:DescribeInstanceTypeOfferings",
                    "ec2:DescribeAvailabilityZones",
                    "ec2:DeleteLaunchTemplate",
                    "ec2:CreateTags",
                    "ec2:CreateLaunchTemplate",
                    "ec2:CreateFleet",
                    "ec2:DescribeSpotPriceHistory",
                    "pricing:GetProducts"
                  ],
                  "Effect": "Allow",
                  "Resource": "*",
                  "Sid": "Karpenter"
                },
                {
                  "Action": "ec2:TerminateInstances",
                  "Condition": {
                    "StringLike": {
                      "ec2:ResourceTag/karpenter.sh/nodepool": "*"
                    }
                  },
                  "Effect": "Allow",
                  "Resource": "*",
                  "Sid": "ConditionalEC2Termination"
                },
                {
                  "Effect": "Allow",
                  "Action": "iam:PassRole",
                  "Resource": "*",
                  "Sid": "PassNodeIAMRole"
                },
                {
                  "Effect": "Allow",
                  "Action": "eks:DescribeCluster",
                  "Resource": "*",
                  "Sid": "EKSClusterEndpointLookup"
                },
                {
                  "Sid": "AllowScopedInstanceProfileCreationActions",
                  "Effect": "Allow",
                  "Resource": "*",
                  "Action": [
                    "iam:CreateInstanceProfile"
                  ]
                },
                {
                  "Sid": "AllowScopedInstanceProfileTagActions",
                  "Effect": "Allow",
                  "Resource": "*",
                  "Action": [
                    "iam:TagInstanceProfile"
                  ]
                },
                {
                  "Sid": "AllowScopedInstanceProfileActions",
                  "Effect": "Allow",
                  "Resource": "*",
                  "Action": [
                    "iam:AddRoleToInstanceProfile",
                    "iam:RemoveRoleFromInstanceProfile",
                    "iam:DeleteInstanceProfile"
                  ]
                },
                {
                  "Sid": "AllowInstanceProfileReadActions",
                  "Effect": "Allow",
                  "Resource": "*",
                  "Action": "iam:GetInstanceProfile"
                }
              ]
            }


  - id: karpenterInstanceProfile
    # dependsOn:
    #   - karpenterControllerRole
    template:
      apiVersion: iam.services.k8s.aws/v1alpha1
      kind: InstanceProfile
      metadata:
        namespace: ${schema.spec.namespace}
        name: ${schema.spec.name}-karpenter-instance-profile
      spec:
        name: ${schema.spec.name}-karpenter-instance-profile
        role: ${schema.spec.name}-cluster-node-role
      
  - id: karpenterInfoCM
    # dependsOn:
    #   - nodeRole
    #   - karpenterControllerRole
    #   - karpenterInstanceProfile
    template:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: ${schema.spec.name}-karpenter-info
        namespace: argocd
      data:
        cluster_name: ${schema.spec.name}
        accountId: ${schema.spec.accountId}
        controller_role_arn: ${karpenterControllerRole.status.ackResourceMetadata.arn}
        node_role_name: ${schema.spec.name}-cluster-node-role
        instance_profile_name: ${schema.spec.name}-karpenter-instance-profile