apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: management-addons
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: eks-controller
        namespace: ack-system
      - name: iam-controller
        namespace: ack-system
      - name: ec2-controller
        namespace: ack-system
      - name: kro
        namespace: kro-system
  template:
    metadata:
      name: 'addon-{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/kumudhanrajan18/gitops-system.git
        targetRevision: HEAD
        path: management/addons/{{name}}
        helm:
          valueFiles:
          - values.yaml
          registrySecrets:
          - name: ecr-credentials
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
