apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: management-addons
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: ack-eks-controller
  template:
    metadata:
      name: ack-eks-controller
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/kumudhanrajan18/gitops-system.git
        targetRevision: HEAD
        path: management/addons/ack
        helm:
          valueFiles:
          - values.yaml
          registrySecrets:
          - name: ecr-credentials
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
