apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: management-addons
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: eks-controller
        namespace: ack-system
        path: management/addons/ack/eks-controller
      - name: iam-controller
        namespace: ack-system
        path: management/addons/ack/iam-controller
      - name: ec2-controller
        namespace: ack-system
        path: management/addons/ack/ec2-controller
      - name: kro
        namespace: kro-system
        path: management/addons/kro
  template:
    metadata:
      name: 'addon-{{name}}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: default
      source:
        repoURL: https://github.com/kumudhanrajan18/gitops-system.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
          - values.yaml
          registrySecrets:
          - name: ecr-credentials
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      dependencies:
        - name: namespaces
