apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kro-resource-groups
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: resource-groups
  template:
    metadata:
      name: 'kro-resource-groups'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: default
      source:
        repoURL: https://github.com/kumudhanrajan18/gitops-system.git
        targetRevision: HEAD
        path: management/kro
      destination:
        server: https://kubernetes.default.svc
        namespace: kro-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
